### ISSUE TITLE
Inquiry about pre-trained AE models in ERGO-II 

### ISSUE THREAD

**Issue by pzhang84** [IdoSpringer/ERGO-II#5]
Hi Ido,

I recently came across your “ERGO-II” paper and I found the idea of using TCR alpha and beta CDR3, MHC typing, VJ genes in peptide binding problems intriguing. Also, the performance in your paper is very impressive! 

I noticed that two pre-trained AE models (one for TCR beta, the other for TCR alpha) were applied in the paper. I am very interested in training the models by myself, however, I may need to compare my models with yours to make sure I did correctly. I wonder if you could kindly share those pre-trained models with me? I was able to easily find the pre-trained AE model for the original ERGO, however I can’t seem to find the pre-trained AE models that were used for ERGO II.

I appreciate your time and look forward to hearing from you soon.
Best regards,

Pengfei Zhang
pzhang84@asu.edu

**Comment by IdoSpringer** [comment]
Hi,
The pre-trained AE model parameters were uploaded:
https://github.com/IdoSpringer/ERGO-II/tree/master/Models/AE

**Comment by pzhang84** [comment]
Thank you for your quick response!
